config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "articles#index"

  resources :articles do
    resources :images
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :images
  validates :name, :content, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
require 'base64'

class ArticlesController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_article, only: [:edit, :show, :update, :destroy]
  
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end
  
  def show
  end

  def create
    @article = Article.new(article_params)
    main_image = params[:article][:main_image]
    if main_image
      @article.main_image = Base64.encode64(main_image.read)
    end

    if @article.save
      flash[:notice] = "The article was saved correctly"
      redirect_to @article
    else
      flash[:error] = "Could not save. Name and content fields must be completed."
      render action: "new"
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      if params[:article][:main_image]
        main_image = params[:article][:main_image]
        main_image = Base64.encode64(main_image.read)
      end
      
      flash[:notice] = "The article was saved correctly"
      @article.update(main_image: main_image)
      redirect_to @article
    else
      flash[:error] = "Could not save. Name and content fields must be completed."
      render action: "edit"
    end
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(
      :name,
      :content,
      :main_image
    )
  end


  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/images_controller.rb
require 'base64'

class ImagesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_article
  before_action :set_image, only: [:edit, :update, :destroy] 

  def new
    @image = @article.images.build
  end

  def create
    @image = @article.images.build(image_params)
    image = params[:image][:image]
    @image.image = Base64.encode64(image.read)

    if @image.save
      redirect_to @article
    else
      render action: "new"
    end
  end

  def edit
  end

  def update
    image = params[:image][:image]

    if @image.update(image: Base64.encode64(image.read))
      redirect_to @article
    else
      render action: "edit"
    end
  end

  def destroy
    @image.destroy

    redirect_to @article
  end

  private

  def image_params
    params.require(:image).permit(:image)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end

  def set_image
    @image = @article.images.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/>
  
  <%= f.label :content %>
  <%= f.text_area :content %><br/>

  <%= f.label :main_image %>
  <%= f.file_field :main_image %><br/>

  <%= f.submit "Save" %>

<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<% if admin_signed_in? %>  
  <%= link_to "New Article", new_article_path %>
<% end %>

<% @articles.each do |article| %>
  <%= link_to article.name, article %><br/>
<% end %>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<h1> <%= @article.name %> </h1>

<% if admin_signed_in? %>  
  <%= link_to "Add image", new_article_image_path(@article) %><br/>
  <%= link_to "Edit", edit_article_path(@article) %><br/>
  <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %><br/>
<% end %>

<p> <%= @article.content %> </p>

<% if @article.main_image %>
  <%= image_tag  "data:image/jpeg;base64," + @article.main_image %>
<% end %>

<% @article.images.each do |image| %>
  <%= image_tag "data:image/jpeg;base64," + image.image %> 
  
  <% if admin_signed_in? %>  
    <%= link_to "Change image", edit_article_image_path(@article, image) %><br/>
    <%= link_to "Delete image", article_image_path(@article, image), method: :delete, data: { confirm: "Are you sure?" } %><br/>
  <% end %>
<% end %>

app/views/images/_form.html.erb
<%= form_for [@article, @image] do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image %><br/>

  <%= f.submit "Save" %>
<% end %>

app/views/images/edit.html.erb
<%= render 'form' %>

app/views/images/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "flash" + name) do %>
        <%= msg %>
      <% end %>
    <% end %>

    <% if admin_signed_in? %>
      <%= link_to "Exit", destroy_admin_session_path %>
    <% else %>
      <%= link_to "Enter", new_admin_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>